### ISSUE TITLE
a unexpected behavior when you remove a current index

### ISSUE THREAD

**Issue by Zahariel1942** [BiosSun/angular-cm-switch#1]
when you remove a panel who is the last and current panel, it's will get a error

```
TypeError: Cannot read property 'el' of undefined
 at cmSwitchContentSliderCtrl.removePanel (switch.js:263)
```

**Comment by BiosSun** [comment]
OK，this is a correct issues. Please you give me a fuck pull requests, bitch.

**Comment by nakating** [comment]
@BiosSun  no, keep it.

**Comment by Zahariel1942** [comment]
@BiosSun merge this #3
